# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e77212c96192b4a10d801847721297bf4ac725861f26695e8156389f72baad4e95d09ebb31f5608e8743e4734a9d9a6ed646ca68664f1916976412914d7dee2

test:
  secret_key_base: 303803c11ca2038d24b4371e70cdcc5cad5a08ff0320a50baba9a6d2b8144195a720fce23987eeff763b564ba6d801e139cb7bc0c4ce77f27ff67a5829e6231f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
